USE [HPINV]
GO
/****** Object:  StoredProcedure [dbo].[usp_YearEndReport]    Script Date: 3/20/2024 4:22:48 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON

DECLARE @yearEndTable TABLE (
	Year INT,
	HcpId INT, -- Not null
	FirstName VARCHAR(20) NULL,
	MiddleName VARCHAR(20) NULL,
	LastName VARCHAR(30) NULL,
	NameSuffix VARCHAR(8) NULL,
	Email VARCHAR(75) NULL,
	UpinNumber VARCHAR(6) NULL,
	BirthDate DATE NULL,
	BirthState VARCHAR(4) NULL,
	BirthCountry VARCHAR(4) NULL,
	CepTeach bit NULL,
	CampusBldg VARCHAR(10) NULL,
	CampusRoom VARCHAR(10) NULL,
	EthnicId INT NULL,
	EthnicOrigin VARCHAR(15) NULL,
	FaxAreaCode INT NULL,
	FaxPhone VARCHAR(8) NULL,
	Gender VARCHAR(4) NULL,
	LicenseNumber VARCHAR(6) NULL,
	NpiNumber VARCHAR(11) NULL,
	Memo VARCHAR(1500) NULL,
	OfficeAreaCode INT NULL,
	OfficePhone VARCHAR(8) NULL,
	SupervisorId INT NULL,
	PresidentsClub VARCHAR(4) NULL,
	WorksiteHistoryId INT, -- Not null
	TypeId VARCHAR(5), -- Not null
	SiteTypeName VARCHAR(40) NULL,
	SiteTypeId INT NULL,
	WorksiteId INT, -- Not null
	WorksiteType VARCHAR(4), -- Not null
	StatusId VARCHAR(4) NULL,
	TransactionId VARCHAR(4) NULL,
	TransferFrom INT NULL,
	TrfCountry VARCHAR(4) NULL,
	TrfState VARCHAR(4) NULL,
	WkHours INT, -- Not null
	WkWeeks INT, -- Not null
	SpecialtyId VARCHAR(7) NULL,
	SpecialtyName VARCHAR(60) NULL,
	Specialty1Id VARCHAR(7) NULL,
	Specialty1 VARCHAR(60) NULL,
	Specialty1Cert INT NULL,
	Specialty1Recert INT NULL,
	Specialty2Id VARCHAR(7) NULL,
	Specialty2 VARCHAR(60) NULL,
	Specialty2Cert INT NULL,
	Specialty2Recert INT NULL,
	Specialty3Id VARCHAR(7) NULL,
	Specialty3 VARCHAR(60) NULL,
	Specialty3Cert INT NULL,
	Specialty3Recert INT NULL,
	ActId INT NULL,
	Activity VARCHAR(40) NULL,
	ArrId INT NULL,
	PracticeArrName VARCHAR(40) NULL,
	Fte VARCHAR(4) NULL,
	EffectDate DATETIME, -- Not null
	AdminDate DATETIME, -- Not null
	ParentWorksite INT NULL,
	ParentWsName VARCHAR(80) NULL,
	WorksiteName VARCHAR(80) NULL,
	Address1 VARCHAR(30) NULL,
	Address2 VARCHAR(30) NULL,
	City VARCHAR(29) NULL,
	CityPop INT NULL,
	CityLatitude DECIMAL(15, 13) NULL,
	CityLongitude DECIMAL(15, 13) NULL,
	SiteLatitude DECIMAL(10, 6) NULL,
	SiteLongitude DECIMAL(10, 6) NULL,
	CountyId INT NULL,
	CountyName VARCHAR(20) NULL,
	CountyPop INT NULL,
	State VARCHAR(4) NULL,
	Zip INT NULL,
	Phone VARCHAR(12) NULL,
	Fax VARCHAR(12) NULL,
	SchoolId INT NULL,
	SchoolName VARCHAR(55) NULL,
	SchoolCity VARCHAR(20) NULL,
	SchoolState VARCHAR(4) NULL,
	SchoolZip VARCHAR(9) NULL,
	DegreeId VARCHAR(5) NULL,
	GradYear INT NULL,
	SubCampusForAdd1 VARCHAR(30) NULL,
	TrfFromWorksiteName VARCHAR(80) NULL,
	TrfFromAddress1 VARCHAR(30) NULL,
	TrfFromAddress2 VARCHAR(30) NULL,
	TrfFromCity VARCHAR(20) NULL,
	TrfFromState VARCHAR(4) NULL,
	TrfFromZip INT NULL,
	TrfFromCityPop INT NULL,
	TrfFromCountyId INT NULL,
	TrfFromCountyName VARCHAR(20) NULL,
	TrfFromCountyPop INT NULL,
	OrigIowaStart DATETIME NULL,
	DeansClub VARCHAR(4) NULL,
	ActiveStatus VARCHAR(3) NULL,
	Res1SpId VARCHAR(7) NULL,
	Res1Specialty VARCHAR(60) NULL,
	Res1SiteId VARCHAR(5) NULL,
	Res1Site VARCHAR(75) NULL,
	Res1City VARCHAR(20) NULL,
	Res1State VARCHAR(4) NULL,
	Res1Country VARCHAR(4) NULL,
	Res1GradYear INT NULL,
	Res2SpId VARCHAR(7) NULL,
	Res2Specialty VARCHAR(60) NULL,
	Res2SiteId VARCHAR(5) NULL,
	Res2Site VARCHAR(75) NULL,
	Res2City VARCHAR(20) NULL,
	Res2State VARCHAR(4) NULL,
	Res2Country VARCHAR(4) NULL,
	Res2GradYear INT NULL,
	Res3SpId VARCHAR(7) NULL,
	Res3Specialty VARCHAR(60) NULL,
	Res3SiteId VARCHAR(5) NULL,
	Res3Site VARCHAR(75) NULL,
	Res3City VARCHAR(20) NULL,
	Res3State VARCHAR(4) NULL,
	Res3Country VARCHAR(4) NULL,
	Res3GradYear INT NULL,
	Fel1SpId VARCHAR(7) NULL,
	Fel1Specialty VARCHAR(60) NULL,
	Fel1SiteId VARCHAR(5) NULL,
	Fel1Site VARCHAR(75) NULL,
	Fel1City VARCHAR(20) NULL,
	Fel1State VARCHAR(4) NULL,
	Fel1Country VARCHAR(4) NULL,
	Fel1GradYear INT NULL,
	Fel2SpId VARCHAR(7) NULL,
	Fel2Specialty VARCHAR(60) NULL,
	Fel2SiteId VARCHAR(5) NULL,
	Fel2Site VARCHAR(75) NULL,
	Fel2City VARCHAR(20) NULL,
	Fel2State VARCHAR(4) NULL,
	Fel2Country VARCHAR(4) NULL,
	Fel2GradYear INT NULL,
	Fel3SpId VARCHAR(7) NULL,
	Fel3Specialty VARCHAR(60) NULL,
	Fel3SiteId VARCHAR(5) NULL,
	Fel3Site VARCHAR(75) NULL,
	Fel3City VARCHAR(20) NULL,
	Fel3State VARCHAR(4) NULL,
	Fel3Country VARCHAR(4) NULL,
	Fel3GradYear INT NULL,
	Title VARCHAR(25) NULL,
	CallDate DATETIME NULL,
	TrSch1Id VARCHAR(5) NULL,
	TrSch1 VARCHAR(75) NULL,
	TrCity1 VARCHAR(20) NULL,
	TrState1 VARCHAR(4) NULL,
	TrGrad1 INT NULL,
	TrId1 VARCHAR(7) NULL,
	Tr1 VARCHAR(60) NULL,
	TrSch2Id VARCHAR(5) NULL,
	TrSch2 VARCHAR(75) NULL,
	TrCity2 VARCHAR(20) NULL,
	TrState2 VARCHAR(4) NULL,
	TrGrad2 INT NULL,
	TrId2 VARCHAR(7) NULL,
	Tr2 VARCHAR(60) NULL,
	TrSch3Id VARCHAR(5) NULL,
	TrSch3 VARCHAR(75) NULL,
	TrCity3 VARCHAR(20) NULL,
	TrState3 VARCHAR(4) NULL,
	TrGrad3 INT NULL,
	TrId3 VARCHAR(7) NULL,
	Tr3 VARCHAR(60) NULL,
	Age INT NULL,
	RoleAbbr VARCHAR(7) NULL,
	RoleName VARCHAR(255) NULL,
	IsPCOWorksite bit NULL,
	IsPCOSpecialty bit NULL,
	FaceTime DECIMAL(4, 1) NULL,
	PctMedicaid DECIMAL(5, 1) NULL,
	LastPcoUpdate DATETIME NULL,
	RuccCode INT NULL,
	PctSlidingFee INT NULL,
	ShowPctSlidingFee INT NULL,
	ZoneCode NCHAR(5) NULL,
	ZoneName NVARCHAR(50) NULL,
	MarComSpecialty VARCHAR(60) NULL,
	DeliveryYear INT NULL,
	DeliveryCount INT NULL,
	SiteLinkId INT
)

DECLARE @endYear VARCHAR(4) = 2025
DECLARE @localWorksiteType VARCHAR(4) = 'P'

DECLARE @hcpTypesTable TABLE (HcpType VARCHAR(3),
							  StartYear INT)
INSERT INTO @hcpTypesTable (HcpType, StartYear)
VALUES ('DDS', 1997)

DECLARE @localHcpType VARCHAR(3)
DECLARE @hcpTypeCursor CURSOR

SET @hcpTypeCursor = CURSOR FOR
	SELECT HcpType FROM @hcpTypesTable

OPEN @hcpTypeCursor

FETCH NEXT FROM @hcpTypeCursor INTO @localHcpType

DECLARE @startYear INT
DECLARE @startYearCursor CURSOR

SET @startYearCursor = CURSOR FOR
	SELECT StartYear FROM @hcpTypesTable

OPEN @startYearCursor

FETCH NEXT FROM @startYearCursor INTO @startYear

DECLARE @localYear VARCHAR(4) = @startYear

WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT 'Beginning processing of ' + @localHcpType
	SET @localYear = @startYear
	WHILE @localYear <= @endYear
	BEGIN

		-- Effect Date
		DECLARE @reportingDate DATE = CAST('12/31/' + @localYear AS DATE);
		PRINT 'Loop Year: ' + CAST(@localYear AS VARCHAR(4));


	;WITH MaxHistory AS (
		SELECT HcpId, WorksiteHistoryId = MAX(WorksiteHistoryId)
		FROM [dbo].[WorksiteHistory]
		WHERE TypeId = @localHcpType
		AND EffectDate <= @reportingDate
		GROUP BY HcpId
	)

	, MaxHistoryBySiteLink AS (
		SELECT HcpId, SiteLinkId, WorksiteHistoryId = MAX(WorksiteHistoryId)
		FROM [dbo].[WorksiteHistory]
		WHERE TypeId = @localHcpType
		AND EffectDate <= @reportingDate
		GROUP BY HcpId, SiteLinkId
	)

	, RelevantHistoryIds AS (
		SELECT sl.WorksiteHistoryId, wh.HcpId
		FROM MaxHistoryBySiteLink sl
		JOIN [dbo].[WorksiteHistory] wh ON wh.WorksiteHistoryId = sl.WorksiteHistoryId
		JOIN [dbo].[Worksite] w ON w.WorksiteId = wh.WorksiteId
		WHERE w.State = 'IA'
		AND wh.WorksiteType = @localWorkSiteType --Primary Only
		AND ( wh.TransactionId <> 'DEL' )
	)
	INSERT INTO @yearEndTable (
			Year,
			HcpId,
			FirstName,
			MiddleName,
			LastName,
			NameSuffix,
			Email,
			UpinNumber,
			BirthDate,
			BirthState,
			BirthCountry,
			CepTeach,
			CampusBldg,
			CampusRoom,
			EthnicId,
			EthnicOrigin,
			FaxAreaCode,
			FaxPhone,
			Gender,
			LicenseNumber,
			NpiNumber,
			Memo,
			OfficeAreaCode,
			OfficePhone,
			SupervisorId,
			PresidentsClub,
			WorksiteHistoryId,
			TypeId,
			SiteTypeName,
			SiteTypeId,
			WorksiteId,
			WorksiteType,
			StatusId,
			TransactionId,
			TransferFrom,
			TrfCountry,
			TrfState,
			WkHours,
			WkWeeks,
			SpecialtyId,
			SpecialtyName,
			Specialty1Id,
			Specialty1,
			Specialty1Cert,
			Specialty1Recert,
			Specialty2Id,
			Specialty2,
			Specialty2Cert,
			Specialty2Recert,
			Specialty3Id,
			Specialty3,
			Specialty3Cert,
			Specialty3Recert,
			ActId,
			Activity,
			ArrId,
			PracticeArrName,
			Fte,
			EffectDate,
			AdminDate,
			ParentWorksite,
			ParentWsName,
			WorksiteName,
			Address1,
			Address2,
			City,
			CityPop,
			CityLatitude,
			CityLongitude,
			SiteLatitude,
			SiteLongitude,
			CountyId,
			CountyName,
			CountyPop,
			State,
			Zip,
			Phone,
			Fax,
			SchoolId,
			SchoolName,
			SchoolCity,
			SchoolState,
			SchoolZip,
			DegreeId,
			GradYear,
			SubCampusForAdd1,
			TrfFromWorksiteName,
			TrfFromAddress1,
			TrfFromAddress2,
			TrfFromCity,
			TrfFromState,
			TrfFromZip,
			TrfFromCityPop,
			TrfFromCountyId,
			TrfFromCountyName,
			TrfFromCountyPop,
			OrigIowaStart,
			DeansClub,
			ActiveStatus,
			Res1SpId,
			Res1Specialty,
			Res1SiteId,
			Res1Site,
			Res1City,
			Res1State,
			Res1Country,
			Res1GradYear,
			Res2SpId,
			Res2Specialty,
			Res2SiteId,
			Res2Site,
			Res2City,
			Res2State,
			Res2Country,
			Res2GradYear,
			Res3SpId,
			Res3Specialty,
			Res3SiteId,
			Res3Site,
			Res3City,
			Res3State,
			Res3Country,
			Res3GradYear,
			Fel1SpId,
			Fel1Specialty,
			Fel1SiteId,
			Fel1Site,
			Fel1City,
			Fel1State,
			Fel1Country,
			Fel1GradYear,
			Fel2SpId,
			Fel2Specialty,
			Fel2SiteId,
			Fel2Site,
			Fel2City,
			Fel2State,
			Fel2Country,
			Fel2GradYear,
			Fel3SpId,
			Fel3Specialty,
			Fel3SiteId,
			Fel3Site,
			Fel3City,
			Fel3State,
			Fel3Country,
			Fel3GradYear,
			Title,
			CallDate,
			TrSch1Id,
			TrSch1,
			TrCity1,
			TrState1,
			TrGrad1,
			TrId1,
			Tr1,
			TrSch2Id,
			TrSch2,
			TrCity2,
			TrState2,
			TrGrad2,
			TrId2,
			Tr2,
			TrSch3Id,
			TrSch3,
			TrCity3,
			TrState3,
			TrGrad3,
			TrId3,
			Tr3,
			Age,
			RoleAbbr,
			RoleName,
			IsPCOWorksite,
			IsPCOSpecialty,
			FaceTime,
			PctMedicaid,
			LastPcoUpdate,
			RuccCode,
			PctSlidingFee,
			ShowPctSlidingFee,
			ZoneCode,
			Zonename,
			MarComSpecialty,
			DeliveryYear,
			DeliveryCount,
			SiteLinkId
		)
	SELECT
		@localYear as Year,
		H.HcpId,
		H.FirstName,
		H.MiddleName,
		H.LastName,
		H.NameSuffix,
		H.Email,
		H.UpinNumber,
		CAST(H.BirthDate AS DATE),
		H.BirthState,
		H.BirthCountry,
		H.CepTeach,
		H.CampusBldg,
		H.CampusRoom,
		H.EthnicId,
		H.EthnicOrigin,
		H.FaxAreaCode,
		H.FaxPhone,
		H.Gender,
		H.LicenseNumber,
		H.NpiNumber,
		H.Memo,
		H.OfficeAreaCode,
		H.OfficePhone,
		H.SupervisorId,
		CASE WHEN H.PresidentsClub = 1 THEN 'Y' ELSE 'N' END AS PresidentsClub,
		H.WorksiteHistoryId,
		H.TypeId,
		H.SiteTypeName,
		H.SiteTypeId,
		H.WorksiteId,
		H.WorksiteType,
		H.StatusId,
		H.TransactionId,
		H.TransferFrom,
		H.TrfCountry,
		H.TrfState,
		H.WkHours,
		H.WkWeeks,
		H.SpecialtyId,
		H.SpecialtyName,
		H.Speclty1Id as Specialty1Id,
		H.Speclty1 as Specialty1,
		H.Speclty1Cert as Specialty1Cert,
		H.Speclty1Recert as Specialty1Recert,
		H.Speclty2Id as Specialty2Id,
		H.Speclty2 as Specialty2,
		H.Speclty2Cert as Specialty2Cert,
		H.Speclty2Recert as Specialty2Recert,
		H.Speclty3Id as Specialty3Id,
		H.Speclty3 as Specialty3,
		H.Speclty3Cert as Specialty3Cert,
		H.Speclty3Recert as Specialty3Recert,
		H.ActId,
		H.Activity,
		H.ArrId,
		H.PracticeArrName,
		H.Fte,
		H.EffectDate,
		H.AdminDate,
		H.ParentWorksite,
		H.ParentWsName,
		H.WorksiteName,
		H.Address1,
		H.Address2,
		H.City,
		H.CityPop,
		H.CityLatitude,
		H.CityLongitude,
		H.SiteLatitude,
		H.SiteLongitude,
		H.CountyId,
		H.CountyName,
		H.CountyPop,
		H.[State],
		H.Zip,
		H.Phone,
		H.Fax,
		H.SchoolId,
		H.SchName as SchoolName,
		H.SchCity as SchoolCity,
		H.SchState as SchoolState,
		H.SchZip as SchoolZip,
		H.DegreeId,
		H.GradYear,
		H.SubCampusForAdd1,
		H.TrfFromWorksiteName,
		H.TrfFromAddress1,
		H.TrfFromAddress2,
		H.TrfFromCity,
		H.TrfFromState,
		H.TrfFromZip,
		H.TrfFromCityPop,
		H.TrfFromCountyId,
		H.TrfFromCountyName,
		H.TrfFromCountyPop,
		H.OrigIowaStart,
		CASE WHEN H.DeansClub = 1 THEN 'Y' ELSE 'N' END AS DeansClub,
		H.ActiveStatus,
		H.Res1SpId,
		H.Res1Specialty,
		H.Res1SiteId,
		H.Res1Site,
		H.Res1City,
		H.Res1State,
		H.Res1Country,
		H.Res1GradYr as Res1GradYear,
		H.Res2SpId,
		H.Res2Specialty,
		H.Res2SiteId,
		H.Res2Site,
		H.Res2City,
		H.Res2State,
		H.Res2Country,
		H.Res2GradYr as Res2GradYear,
		H.Res3SpId,
		H.Res3Specialty,
		H.Res3SiteId,
		H.Res3Site,
		H.Res3City,
		H.Res3State,
		H.Res3Country,
		H.Res3GradYr as Res3GradYear,
		H.Fel1SpId,
		H.Fel1Specialty,
		H.Fel1SiteId,
		H.Fel1Site,
		H.Fel1City,
		H.Fel1State,
		H.Fel1Country,
		H.Fel1GradYr as Fel1GradYear,
		H.Fel2SpId,
		H.Fel2Specialty,
		H.Fel2SiteId,
		H.Fel2Site,
		H.Fel2City,
		H.Fel2State,
		H.Fel2Country,
		H.Fel2GradYr as Fel2GradYear,
		H.Fel3SpId,
		H.Fel3Specialty,
		H.Fel3SiteId,
		H.Fel3Site,
		H.Fel3City,
		H.Fel3State,
		H.Fel3Country,
		H.Fel3GradYr as Fel3GradYear,
		H.Title,
		H.CallDate,
		H.TrSch1Id,
		H.TrSch1,
		H.TrCity1,
		H.TrState1,
		H.TrGrad1,
		H.TrId1,
		H.Tr1,
		H.TrSch2Id,
		H.TrSch2,
		H.TrCity2,
		H.TrState2,
		H.TrGrad2,
		H.TrId2,
		H.Tr2,
		H.TrSch3Id,
		H.TrSch3,
		H.TrCity3,
		H.TrState3,
		H.TrGrad3,
		H.TrId3,
		H.Tr3,

		CASE
			WHEN H.BirthDate IS NULL THEN NULL
			ELSE ABS(DATEDIFF(MONTH, CAST(@localYear AS DATE), CAST(CAST(DATEPART(YEAR, H.BirthDate) AS NVARCHAR(4)) AS DATE))) / 12
		END AS Age,
		H.RoleAbbr,
		H.RoleName,
		IsPCOWorksite ,
		IsPCOSpecialty ,
		FaceTime ,
		PctMedicaid ,
		LastPcoUpdate ,
		H.RuccCode,
		H.PctSlidingFee,
		ShowPctSlidingFee =
			CASE WHEN H.TypeId IN ('PHY', 'DDS') THEN 2
				ELSE 0
			END,
		H.ZoneCode,
		H.ZoneName,
		H.MarComSpecialty,

		DeliveryYear = del.Year,
		DeliveryCount = del.DeliveryCount,
		H.SiteLinkId
	FROM dbo.HistoryComplete h
	LEFT OUTER JOIN [dbo].[HcpDelivery] del ON del.HcpId = h.HcpId AND Year = @localYear

	WHERE h.WorksiteHistoryId IN (SELECT rh.WorksiteHistoryId FROM RelevantHistoryIds rh)
	
	SET @localYear = @localYear + 1
	END

	PRINT 'Finished processing HcpType ' + @localHcpType
	FETCH NEXT FROM @hcpTypeCursor INTO @localHcpType
	FETCH NEXT FROM @startYearCursor INTO @startYear

END;

SELECT Year, HcpId, Age, WorksiteId, PracticeArrName, SpecialtyName, WkWeeks, WkHours, Fte, WorksiteType
FROM @yearEndTable
WHERE TypeId = 'DDS'
